### ISSUE TITLE
Prefixes error

### ISSUE THREAD

**Issue by troke12** [dominik-korsa/discord-integration#1]
![image](https://user-images.githubusercontent.com/10250068/118360431-09545b80-b5ba-11eb-8d9b-846468ee2785.png)
some of groups have a prefix, the messages delivery to the Discord it's really not readable, any solutions?

**Comment by troke12** [comment]
got some warn on the consoles
![image](https://user-images.githubusercontent.com/10250068/118360832-7b797000-b5bb-11eb-9294-8ec44195b06a.png)

**Comment by dominik-korsa** [comment]
Fixed in 6d502c13d53a4ccdfa3cf4c05f737e881e6050c4
