### ISSUE TITLE
[Future Request] Account Mapping

### ISSUE THREAD

**Issue by kyledavis124** [dominik-korsa/discord-integration#10]
# Issue

Running the command, /di claim, in Minecraft would generate a code, in Minecraft, which could be used in discord for a brief period, linking a Minecraft account to a Discord account.

This link could be optionally required <- needs more thought.

# Use Cases

- A look-up table for potential future features.
  - You could expose the lookup as an end point for other developers to add onto this plugin with modularity. You would not have to support all the features in one repo. Each future being its own plugin. Meaning new features are less likely to break existing features.
- #9

**Comment by dominik-korsa** [comment]
Thanks for the suggestion!

To be honest I don't see a point in adding this at the moment. The plugin currently doesn't provide any way for interfacing with other plugins and I don't really want to burden myself with the need to provide the version compatibility level and making a stable API. That being said if any plugin developer wants to integrate their plugin with DI please let me know.

I also don't think it provides any benefit to the blocking feature, as Minecraft players are only gonna block Discord users anyway.
