### ISSUE TITLE
[Bug] User id instead of nickname when pinging

### ISSUE THREAD

**Issue by Notes871** [dominik-korsa/discord-integration#11]
Hi there
I see a uuid in the chat, what can I do?

**Comment by FlyGuyGo** [comment]
If you are referring to the Discord user ID number seen in Minecraft chat when someone mentions someone, which looks like <@!112398217398213>, that is normal. Perhaps he could make it show the @Name instead but you would have to suggest that to him. If you are referring to something else you will have to provide more detail for him to help you.

**Comment by dominik-korsa** [comment]
I'm working on this at this very moment :)

**Comment by dominik-korsa** [comment]
Fixed in 2ad5755d06ce2be0c82528171af892fd0535009d, released in **v2.4.0**
