### ISSUE TITLE
[Bug] Status Showing as Idle

### ISSUE THREAD

**Issue by FlyGuyGo** [dominik-korsa/discord-integration#12]
Sometimes the status of my bot, using this plugin, shows as Idle. It didn't used to do this in the previous version. This a minor bug but nonetheless I wanted to bring it to your attention.

**Comment by aszancer** [comment]
This is a specially implemented feature, not a bug. When there are zero players online the bot status automatically changes to Idle. When someone later joins the server the status will change back to Online.

**Comment by dominik-korsa** [comment]
**It's not a bug, it's a feature** 😄 
You can always disable it by setting the `activity.idle-when-no-players-online` to `false` (keep in mind you might have to add this line to the config)

**Comment by dominik-korsa** [comment]
https://github.com/dominik-korsa/discord-integration/blob/main/src/main/resources/config.yml#L51

**Comment by FlyGuyGo** [comment]
Thank you for pointing out the extra config option!
