### ISSUE TITLE
Webhooks able to mention @everyone or @here.

### ISSUE THREAD

**Issue by jackomix** [dominik-korsa/discord-integration#3]
Even with every permission for roles and channels not allowing mentions, the MC to Discord chat (which uses webhooks) is able to mention @everyone or @here. And since server owners can't disable mentions in webhooks, there'll have to be some function to remove mentions from messages when they're sent to Discord.

**Comment by dominik-korsa** [comment]
Fixed in 6d502c13d53a4ccdfa3cf4c05f737e881e6050c4. For now I disabled pings in webhooks completely, I might add full ping support and config field later. The fix is included in v2.0.1
