### ISSUE TITLE
Server stuck when stoping server sometimes

### ISSUE THREAD

**Issue by CuteyCang** [dominik-korsa/discord-integration#4]
When I stoping server,  it stuck my server sometimes.
Windows 10 home 64x
PaperMC-1.17.1-279 
JDK-16.0.2.7-hotspot

server log just stuck at:
`[06:59:41] [Server thread/INFO]: [DiscordIntegration] Disabling DiscordIntegration v2.1.0`
(No more log after it and no error log  before it.)

**Comment by dominik-korsa** [comment]
(Crudely) fixed in 9980e7d262bbd03841d4cb19757657242a6ad47e
