### ISSUE TITLE
[Bug] Erroneous Color Code Symbol

### ISSUE THREAD

**Issue by FlyGuyGo** [dominik-korsa/discord-integration#7]
When a message is sent to Discord it will show the color code used by my chat manager. Perhaps you could exclude "§" and the proceeding character from showing?
![image](https://user-images.githubusercontent.com/85654654/151470409-6fab4670-b1e8-4351-88bd-982ec44103bc.png)

**Comment by dominik-korsa** [comment]
Fixed in a98541b93e004a545c399219e56c230cf782f4bb, released in v2.3.0
